version: '3'
services:
    app:
        container_name: gos-project-app
        restart: always
        build: .
        volumes:
            - ../uploads:/gos-project/uploads
            - /etc/letsencrypt:/etc/letsencrypt:ro
        ports:
            - '7000:3000'
        links:
            - mongo
    mongo:
        container_name: gos-project-mongo
        image: mongo:5.0
        volumes:
            - /etc/mongod.conf:/etc/mongod.conf
            - ../mongodata:/data/db
        ports:
            - '27217:27017'
